services:
  - type: web
    name: notepad
    env: php
    region: oregon
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
      npm install
      npm run prod
    startCommand: "service nginx start && php-fpm"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-cs4penjqf0us73b61u0g-a
      - key: DB_DATABASE
        value: notepad_dzby
      - key: DB_USERNAME
        value: notepad
      - key: DB_PASSWORD
        value: hXwURjLT6fSaKFsNrnsPYpMGheqpdsuU
    plan: standard
    ports:
      - "80:80"

