name: Deploy to InfinityFree

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./  # Directory to deploy from
          server-dir: /htdocs/    # Directory on the server (root)
